# Generated by Django 3.1.3 on 2020-11-24 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
