# Generated by Django 3.1.3 on 2020-11-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20201124_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genreAlt',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='movie',
            name='repGenreNm',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='typeNm',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
