# Generated by Django 3.1.3 on 2020-11-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieCd', models.CharField(max_length=50)),
                ('movieNm', models.CharField(max_length=50)),
                ('movieNmEn', models.CharField(max_length=50)),
                ('prdtYear', models.CharField(max_length=50)),
                ('openDt', models.CharField(max_length=50)),
                ('typeNm', models.CharField(max_length=50)),
                ('prdtStatNm', models.CharField(max_length=50)),
                ('nationAlt', models.CharField(max_length=50)),
                ('genreAlt', models.CharField(max_length=50)),
                ('repNationNm', models.CharField(max_length=50)),
                ('repGenreNm', models.CharField(max_length=50)),
            ],
        ),
    ]
