# Generated by Django 3.1.3 on 2020-11-22 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieCd', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('movieNm', models.CharField(max_length=50)),
                ('movieNmEn', models.CharField(blank=True, max_length=100)),
                ('prdtYear', models.CharField(max_length=10)),
                ('openDt', models.CharField(blank=True, max_length=10)),
                ('typeNm', models.CharField(max_length=10)),
                ('prdtStatNm', models.CharField(blank=True, max_length=10)),
                ('nationAlt', models.CharField(blank=True, max_length=30)),
                ('genreAlt', models.CharField(max_length=30)),
                ('repNationNm', models.CharField(blank=True, max_length=10)),
                ('repGenreNm', models.CharField(max_length=10)),
                ('posterSrc', models.TextField(null=True)),
                ('popularity', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=10)),
                ('photo', models.TextField()),
                ('movies', models.ManyToManyField(related_name='peoples', to='movies.Movie')),
            ],
        ),
    ]
