# Generated by Django 3.1.3 on 2020-11-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201119_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='companyNm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='directorNm',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
