# Generated by Django 3.1.3 on 2020-11-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201119_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='companyNm',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='directorNm',
        ),
        migrations.AddField(
            model_name='movie',
            name='companys',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
