# Generated by Django 3.1.3 on 2020-11-24 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201123_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoviescore',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
