# Generated by Django 3.1.3 on 2020-11-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_remove_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='prdtYear',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
