# Generated by Django 3.1.3 on 2020-11-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_review_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='posterSrc',
            field=models.TextField(null=True),
        ),
    ]
