# Generated by Django 3.1.3 on 2020-11-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_postersrc'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
